[package]
name = "keepitsimple"
version = "0.1.0"
authors = ["Dylan Thinnes <dylan.thinnes@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1.0"
pest = "2.1.3"
pest_derive = "2.1.0"
